# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env


networks:
  default: development
  development:
    cmd_settings:
      mnemonic: this claw debris fuel future fashion cloth velvet road swim dune embody
      default_balance: 200000
      unlock: 0x38848f3A9e14B51A6dBC9023a94854d144c172cc 

    update_interval: 60
    verify: False
  
  kovan:

    verify: False
    update_interval: 60


wallets:
  from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true
